export class NavigationService {
  navigationItems = [
    {
      name:"home",
      tooltipText:"Home",
      href:"#",
      image:"/assets/images/ClickHome.svg",
      alt:"Home",
      target:"_self",
    },
    {
      name:"phone",
      tooltipText:"Call",
      href:"#",
      image:"/assets/images/ClickPhone.svg",
      alt:"Phone",
      target:"_self",
    },
    {
      name:"mail",
      tooltipText:"Write",
      href:"mailto:limoragam@gmail.com",
      image:"/assets/images/ClickGmail.svg",
      alt:"Mail",
      target:"_self",
    },
    {
      name:"facebook",
      tooltipText:"Like",
      href:"https://www.facebook.com/limor.agam.9",
      image:"/assets/images/ClickFacebook.svg",
      alt:"Facebook",
      target:"_blank"
    },
    {
      name:"instagram",
      tooltipText:"Follow",
      href:"https://www.instagram.com/limoragam/",
      image:"/assets/images/ClickInstagram.svg",
      alt:"Instagram",
      target:"_blank",
    },
    {
      name:"about",
      tooltipText:"About",
      href:"#about",
      image:"/assets/images/ClickLick.svg",
      alt:"About",
      target:"_self",
    },
  ]
}
